version: "3.1"

services:
  twitch-farmer-api:
    build: './twitch-farmer-api'
    container_name: alo
    networks:
      - geral
    ports:
      - 80
    environment:
      - DATABASE_HOST=$DATABASE_HOSTA

networks:
  geral:
    driver: bridge