version: "3.1"

services:
  twitch-farmer-api:
    build: './twitch-farmer-api'
    networks:
      - geral
    ports:
      - 80
    environment:
      - TWITCH_FARMER_API_DATABASE_HOST
      - TWITCH_FARMER_API_DATABASE_PORT
      - TWITCH_FARMER_API_DATABASE_USERNAME
      - TWITCH_FARMER_API_DATABASE_PASSWORD
      - TWITCH_FARMER_API_DATABASE_DATABASE
      - TWITCH_FARMER_API_JWT_SECRET
      - TWITCH_FARMER_API_TWITCH_CLIENT_ID
      - TWITCH_FARMER_API_TWITCH_CLIENT_SECRET

networks:
  geral:
    driver: bridge