version: "3.1"

services:
  twitch-farmer-api:
    build: './twitch-farmer-api'
    container_name: alo
    networks:
      - geral
    environment:
      - teste

networks:
  geral:
    driver: bridge