version: "3.1"

services:
  twitch-farmer-api:
    build: './twitch-farmer-api'
    container_name: alo
    networks:
      - geral
    ports:
      - 80
    environment:
      - DATABASE_HOST=$DATABASE_HOSTA
      - DATABASE_PORT
      - DATABASE_USERNAME
      - DATABASE_PASSWORD
      - DATABASE_DATABASE
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_PASSWORD

networks:
  geral:
    driver: bridge